/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareerOutcomesRouteImport } from './routes/career-outcomes'
import { Route as CohortPlannerRouteImport } from './routes/cohort-planner'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CreditMappingRouteImport } from './routes/credit-mapping'
import { Route as EmailPreviewRouteImport } from './routes/email-preview'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FounderReviewRouteImport } from './routes/founder-review'
import { Route as IndustryPartnerRouteImport } from './routes/industry-partner'
import { Route as IndustryReadinessRouteImport } from './routes/industry-readiness'
import { Route as ManageResultRouteImport } from './routes/manageResult'
import { Route as MentorFrameworkRouteImport } from './routes/mentor-framework'
import { Route as OutcomesRouteImport } from './routes/outcomes'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as ProgramGovernanceRouteImport } from './routes/program-governance'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as StartupResidencyRouteImport } from './routes/startup-residency'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as SyllabusOverviewRouteImport } from './routes/syllabus-overview'
import { Route as WeeklyFrameworkRouteImport } from './routes/weekly-framework'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerOutcomesRoute = CareerOutcomesRouteImport.update({
  id: '/career-outcomes',
  path: '/career-outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortPlannerRoute = CohortPlannerRouteImport.update({
  id: '/cohort-planner',
  path: '/cohort-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditMappingRoute = CreditMappingRouteImport.update({
  id: '/credit-mapping',
  path: '/credit-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailPreviewRoute = EmailPreviewRouteImport.update({
  id: '/email-preview',
  path: '/email-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderReviewRoute = FounderReviewRouteImport.update({
  id: '/founder-review',
  path: '/founder-review',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryPartnerRoute = IndustryPartnerRouteImport.update({
  id: '/industry-partner',
  path: '/industry-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryReadinessRoute = IndustryReadinessRouteImport.update({
  id: '/industry-readiness',
  path: '/industry-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageResultRoute = ManageResultRouteImport.update({
  id: '/manageResult',
  path: '/manageResult',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorFrameworkRoute = MentorFrameworkRouteImport.update({
  id: '/mentor-framework',
  path: '/mentor-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesRoute = OutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramGovernanceRoute = ProgramGovernanceRouteImport.update({
  id: '/program-governance',
  path: '/program-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupResidencyRoute = StartupResidencyRouteImport.update({
  id: '/startup-residency',
  path: '/startup-residency',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusOverviewRoute = SyllabusOverviewRouteImport.update({
  id: '/syllabus-overview',
  path: '/syllabus-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyFrameworkRoute = WeeklyFrameworkRouteImport.update({
  id: '/weekly-framework',
  path: '/weekly-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/career-outcomes': typeof CareerOutcomesRoute
  '/cohort-planner': typeof CohortPlannerRoute
  '/command-center': typeof CommandCenterRoute
  '/credit-mapping': typeof CreditMappingRoute
  '/email-preview': typeof EmailPreviewRoute
  '/evaluation': typeof EvaluationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founder-review': typeof FounderReviewRoute
  '/industry-partner': typeof IndustryPartnerRoute
  '/industry-readiness': typeof IndustryReadinessRoute
  '/manageResult': typeof ManageResultRoute
  '/mentor-framework': typeof MentorFrameworkRoute
  '/outcomes': typeof OutcomesRoute
  '/philosophy': typeof PhilosophyRoute
  '/program-governance': typeof ProgramGovernanceRoute
  '/proposal': typeof ProposalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/roadmap': typeof RoadmapRoute
  '/startup-residency': typeof StartupResidencyRoute
  '/syllabus': typeof SyllabusRoute
  '/syllabus-overview': typeof SyllabusOverviewRoute
  '/weekly-framework': typeof WeeklyFrameworkRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/career-outcomes': typeof CareerOutcomesRoute
  '/cohort-planner': typeof CohortPlannerRoute
  '/command-center': typeof CommandCenterRoute
  '/credit-mapping': typeof CreditMappingRoute
  '/email-preview': typeof EmailPreviewRoute
  '/evaluation': typeof EvaluationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founder-review': typeof FounderReviewRoute
  '/industry-partner': typeof IndustryPartnerRoute
  '/industry-readiness': typeof IndustryReadinessRoute
  '/manageResult': typeof ManageResultRoute
  '/mentor-framework': typeof MentorFrameworkRoute
  '/outcomes': typeof OutcomesRoute
  '/philosophy': typeof PhilosophyRoute
  '/program-governance': typeof ProgramGovernanceRoute
  '/proposal': typeof ProposalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/roadmap': typeof RoadmapRoute
  '/startup-residency': typeof StartupResidencyRoute
  '/syllabus': typeof SyllabusRoute
  '/syllabus-overview': typeof SyllabusOverviewRoute
  '/weekly-framework': typeof WeeklyFrameworkRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/career-outcomes': typeof CareerOutcomesRoute
  '/cohort-planner': typeof CohortPlannerRoute
  '/command-center': typeof CommandCenterRoute
  '/credit-mapping': typeof CreditMappingRoute
  '/email-preview': typeof EmailPreviewRoute
  '/evaluation': typeof EvaluationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founder-review': typeof FounderReviewRoute
  '/industry-partner': typeof IndustryPartnerRoute
  '/industry-readiness': typeof IndustryReadinessRoute
  '/manageResult': typeof ManageResultRoute
  '/mentor-framework': typeof MentorFrameworkRoute
  '/outcomes': typeof OutcomesRoute
  '/philosophy': typeof PhilosophyRoute
  '/program-governance': typeof ProgramGovernanceRoute
  '/proposal': typeof ProposalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/roadmap': typeof RoadmapRoute
  '/startup-residency': typeof StartupResidencyRoute
  '/syllabus': typeof SyllabusRoute
  '/syllabus-overview': typeof SyllabusOverviewRoute
  '/weekly-framework': typeof WeeklyFrameworkRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/career-outcomes'
    | '/cohort-planner'
    | '/command-center'
    | '/credit-mapping'
    | '/email-preview'
    | '/evaluation'
    | '/forgot-password'
    | '/founder-review'
    | '/industry-partner'
    | '/industry-readiness'
    | '/manageResult'
    | '/mentor-framework'
    | '/outcomes'
    | '/philosophy'
    | '/program-governance'
    | '/proposal'
    | '/reset-password'
    | '/result'
    | '/roadmap'
    | '/startup-residency'
    | '/syllabus'
    | '/syllabus-overview'
    | '/weekly-framework'
    | '/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/career-outcomes'
    | '/cohort-planner'
    | '/command-center'
    | '/credit-mapping'
    | '/email-preview'
    | '/evaluation'
    | '/forgot-password'
    | '/founder-review'
    | '/industry-partner'
    | '/industry-readiness'
    | '/manageResult'
    | '/mentor-framework'
    | '/outcomes'
    | '/philosophy'
    | '/program-governance'
    | '/proposal'
    | '/reset-password'
    | '/result'
    | '/roadmap'
    | '/startup-residency'
    | '/syllabus'
    | '/syllabus-overview'
    | '/weekly-framework'
    | '/course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/career-outcomes'
    | '/cohort-planner'
    | '/command-center'
    | '/credit-mapping'
    | '/email-preview'
    | '/evaluation'
    | '/forgot-password'
    | '/founder-review'
    | '/industry-partner'
    | '/industry-readiness'
    | '/manageResult'
    | '/mentor-framework'
    | '/outcomes'
    | '/philosophy'
    | '/program-governance'
    | '/proposal'
    | '/reset-password'
    | '/result'
    | '/roadmap'
    | '/startup-residency'
    | '/syllabus'
    | '/syllabus-overview'
    | '/weekly-framework'
    | '/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CareerOutcomesRoute: typeof CareerOutcomesRoute
  CohortPlannerRoute: typeof CohortPlannerRoute
  CommandCenterRoute: typeof CommandCenterRoute
  CreditMappingRoute: typeof CreditMappingRoute
  EmailPreviewRoute: typeof EmailPreviewRoute
  EvaluationRoute: typeof EvaluationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FounderReviewRoute: typeof FounderReviewRoute
  IndustryPartnerRoute: typeof IndustryPartnerRoute
  IndustryReadinessRoute: typeof IndustryReadinessRoute
  ManageResultRoute: typeof ManageResultRoute
  MentorFrameworkRoute: typeof MentorFrameworkRoute
  OutcomesRoute: typeof OutcomesRoute
  PhilosophyRoute: typeof PhilosophyRoute
  ProgramGovernanceRoute: typeof ProgramGovernanceRoute
  ProposalRoute: typeof ProposalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultRoute: typeof ResultRoute
  RoadmapRoute: typeof RoadmapRoute
  StartupResidencyRoute: typeof StartupResidencyRoute
  SyllabusRoute: typeof SyllabusRoute
  SyllabusOverviewRoute: typeof SyllabusOverviewRoute
  WeeklyFrameworkRoute: typeof WeeklyFrameworkRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-outcomes': {
      id: '/career-outcomes'
      path: '/career-outcomes'
      fullPath: '/career-outcomes'
      preLoaderRoute: typeof CareerOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort-planner': {
      id: '/cohort-planner'
      path: '/cohort-planner'
      fullPath: '/cohort-planner'
      preLoaderRoute: typeof CohortPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-mapping': {
      id: '/credit-mapping'
      path: '/credit-mapping'
      fullPath: '/credit-mapping'
      preLoaderRoute: typeof CreditMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-preview': {
      id: '/email-preview'
      path: '/email-preview'
      fullPath: '/email-preview'
      preLoaderRoute: typeof EmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-review': {
      id: '/founder-review'
      path: '/founder-review'
      fullPath: '/founder-review'
      preLoaderRoute: typeof FounderReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-partner': {
      id: '/industry-partner'
      path: '/industry-partner'
      fullPath: '/industry-partner'
      preLoaderRoute: typeof IndustryPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-readiness': {
      id: '/industry-readiness'
      path: '/industry-readiness'
      fullPath: '/industry-readiness'
      preLoaderRoute: typeof IndustryReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manageResult': {
      id: '/manageResult'
      path: '/manageResult'
      fullPath: '/manageResult'
      preLoaderRoute: typeof ManageResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-framework': {
      id: '/mentor-framework'
      path: '/mentor-framework'
      fullPath: '/mentor-framework'
      preLoaderRoute: typeof MentorFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes': {
      id: '/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof OutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-governance': {
      id: '/program-governance'
      path: '/program-governance'
      fullPath: '/program-governance'
      preLoaderRoute: typeof ProgramGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-residency': {
      id: '/startup-residency'
      path: '/startup-residency'
      fullPath: '/startup-residency'
      preLoaderRoute: typeof StartupResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus-overview': {
      id: '/syllabus-overview'
      path: '/syllabus-overview'
      fullPath: '/syllabus-overview'
      preLoaderRoute: typeof SyllabusOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-framework': {
      id: '/weekly-framework'
      path: '/weekly-framework'
      fullPath: '/weekly-framework'
      preLoaderRoute: typeof WeeklyFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CareerOutcomesRoute: CareerOutcomesRoute,
  CohortPlannerRoute: CohortPlannerRoute,
  CommandCenterRoute: CommandCenterRoute,
  CreditMappingRoute: CreditMappingRoute,
  EmailPreviewRoute: EmailPreviewRoute,
  EvaluationRoute: EvaluationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FounderReviewRoute: FounderReviewRoute,
  IndustryPartnerRoute: IndustryPartnerRoute,
  IndustryReadinessRoute: IndustryReadinessRoute,
  ManageResultRoute: ManageResultRoute,
  MentorFrameworkRoute: MentorFrameworkRoute,
  OutcomesRoute: OutcomesRoute,
  PhilosophyRoute: PhilosophyRoute,
  ProgramGovernanceRoute: ProgramGovernanceRoute,
  ProposalRoute: ProposalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultRoute: ResultRoute,
  RoadmapRoute: RoadmapRoute,
  StartupResidencyRoute: StartupResidencyRoute,
  SyllabusRoute: SyllabusRoute,
  SyllabusOverviewRoute: SyllabusOverviewRoute,
  WeeklyFrameworkRoute: WeeklyFrameworkRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
