-- Ensure proposal table has RLS policies for update and auto venture creation

CREATE TABLE IF NOT EXISTS public.proposal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  email text NOT NULL,
  subject text NOT NULL,
  venture text NOT NULL,
  status text DEFAULT 'pending'
);

ALTER TABLE public.proposal ENABLE ROW LEVEL SECURITY;

-- Allow reading, inserting, and updating proposals
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'proposal' AND policyname = 'Allow select for all'
  ) THEN
    CREATE POLICY "Allow select for all" ON public.proposal FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'proposal' AND policyname = 'Allow insert for all'
  ) THEN
    CREATE POLICY "Allow insert for all" ON public.proposal FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'proposal' AND policyname = 'Allow update for authenticated'
  ) THEN
    CREATE POLICY "Allow update for authenticated" ON public.proposal FOR UPDATE USING (true) WITH CHECK (true);
  END IF;
END $$;

-- Enable grants
GRANT ALL ON public.proposal TO authenticated;
GRANT ALL ON public.proposal TO anon;
GRANT ALL ON public.proposal TO service_role;
